"""Bake one recorded episode's action column into a literal Python module.

This is the "hardcoding" step: it turns rows of a LeRobotDataset parquet into a
`hardcoded_episode.py` that `dummy_policy_server` imports, so the served trajectory is
plain source you can read, diff, edit and commit - no dataset, no network, no HF cache at
serve time. Reads the parquet directly, so the (large) video files need not be downloaded.

Fetch the dataset first (meta + data only). NOT into $SHARE/lerobot_data: that root belongs
to lerobot_recorder, and a directory sitting there with no meta/ makes LeRobotDataset.create
fail with `[Errno 17] File exists`, so MENU refuses to start an episode.
```shell
python3 -c "from huggingface_hub import snapshot_download; snapshot_download(
    repo_id='khoviadin/grab_and_place_cube', repo_type='dataset',
    local_dir='/home/ros/share/hf_datasets/grab_and_place_cube',
    allow_patterns=['meta/**','data/**'])"
```
Then:
```shell
python3 export_episode_actions.py \
    --root=/home/ros/share/hf_datasets/grab_and_place_cube --episode=52 \
    --out=hardcoded_episode.py
```
`--episode` with no value ranks every episode by peak joint speed and prints the table,
which is how episode 52 was chosen: recorded teleop is far less smooth than a hand-authored
ramp, and a jerky episode replays as a jerky command stream.
"""

import argparse
import json
import pathlib

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq


def load(root: pathlib.Path):
    info = json.loads((root / "meta" / "info.json").read_text())
    files = sorted((root / "data").rglob("*.parquet"))
    if not files:
        raise SystemExit(f"no data/**/*.parquet under {root}")
    table = pa.concat_tables([pq.read_table(f) for f in files]).to_pandas()
    actions = np.stack(table["action"].to_numpy()).astype(np.float64)
    return info, actions, table["episode_index"].to_numpy()


def summarize(info, actions, episodes) -> None:
    fps = info["fps"]
    print(f"{'ep':>4} {'frames':>7} {'secs':>6} {'peak rad/s':>11} {'p99 rad/s':>10} {'grip cycles':>12}")
    rows = []
    for e in np.unique(episodes):
        a = actions[episodes == e]
        step = np.abs(np.diff(a[:, :-1], axis=0))
        grip = a[:, -1]
        closes = int(((grip[:-1] > 0.05) & (grip[1:] <= 0.05)).sum())
        rows.append((e, len(a), step.max() * fps, np.percentile(step, 99) * fps, closes))
    for e, n, peak, p99, closes in sorted(rows, key=lambda r: r[2]):
        print(f"{e:>4} {n:>7} {n / fps:>6.1f} {peak:>11.2f} {p99:>10.2f} {closes:>12}")
    print(f"\n{len(rows)} episodes, sorted by peak joint speed (smoothest first).")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--root", required=True, help="local dataset root (holds meta/ and data/)")
    p.add_argument("--repo_id", default="", help="recorded in the generated header for provenance")
    p.add_argument("--revision", default="", help="dataset commit sha, likewise")
    p.add_argument("--episode", type=int, default=None, help="omit to rank every episode and exit")
    p.add_argument("--out", default="hardcoded_episode.py")
    p.add_argument("--decimals", type=int, default=6, help="1e-6 rad is ~1e-4 deg, far under encoder resolution")
    args = p.parse_args()

    root = pathlib.Path(args.root)
    info, actions, episodes = load(root)

    if args.episode is None:
        summarize(info, actions, episodes)
        return

    fps = info["fps"]
    names = list(info["features"]["action"]["names"])
    selected = actions[episodes == args.episode]
    if not len(selected):
        raise SystemExit(f"episode {args.episode} not found (have {episodes.min()}..{episodes.max()})")

    rounded = np.round(selected, args.decimals)
    rounding_error = float(np.abs(rounded - selected).max())
    step = np.abs(np.diff(rounded[:, :-1], axis=0))
    peak_rad_s = float(step.max()) * fps
    tasks = pq.read_table(root / "meta" / "tasks.parquet").to_pandas()
    task = str(tasks.index[0]) if len(tasks.index) else ""

    lines = [
        '"""GENERATED by export_episode_actions.py - regenerate rather than edit by hand.',
        "",
        f"Source   : {args.repo_id or root.name}"
        + (f" @ {args.revision[:12]}" if args.revision else "")
        + f", episode {args.episode}",
        f'Task     : "{task}"',
        f"Robot    : {info.get('robot_type')}   ({len(names)}-dim action)",
        f"Frames   : {len(selected)} @ {fps} fps = {len(selected) / fps:.2f} s",
        f"Peak     : {peak_rad_s:.2f} rad/s between consecutive rows",
        f"Rounding : {args.decimals} decimals, max deviation from the recording {rounding_error:.2e}",
        "",
        "These are the RECORDED COMMANDS (what the teleop sent to the arm), not the measured",
        "positions - i.e. the same `action` column a policy is trained to predict. Column order",
        "is the dataset's action.names, which is exactly MantisFollower.action_features: arm",
        "joints in RADIANS, gripper opening WIDTH in METRES.",
        '"""',
        "",
        f"FPS = {fps}",
        f"EPISODE = {args.episode}",
        f"SOURCE = {(args.repo_id or str(root)) + (f'@{args.revision}' if args.revision else '')!r}",
        f"TASK = {task!r}",
        "",
        "ACTION_NAMES = [",
        *[f"    {n!r}," for n in names],
        "]",
        "",
        "# fmt: off",
        "ACTIONS = [",
    ]
    width = args.decimals + 4
    for i, row in enumerate(rounded):
        values = ", ".join(f"{v:>{width}.{args.decimals}f}" for v in row)
        lines.append(f"    ({values}),  # {i:>3}  t={i / fps:>6.3f}s")
    lines += ["]", "# fmt: on", ""]

    pathlib.Path(args.out).write_text("\n".join(lines))
    print(f"Wrote {args.out}: {len(selected)} rows x {len(names)} cols, peak {peak_rad_s:.2f} rad/s")


if __name__ == "__main__":
    main()
